[tools]
"cargo:wasm-pack" = "0.13.1"
node = "22"
pnpm = "latest"
hyperfine = "latest"

[tasks.compile]
run = "cargo build"

[tasks.'docker:build']
run = "bash .devcontainer/test-docker-build.sh"

[tasks.'docker:run']
run = "docker run -it --rm test-devcontainer:latest bash"
